# Generated by Django 4.1 on 2022-08-24 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=50)),
                ('employee_lastname', models.CharField(max_length=50)),
                ('employee_dob', models.DateField()),
                ('employee_adress', models.CharField(max_length=100)),
                ('employee_nationality', models.CharField(max_length=50)),
                ('employee_dni', models.IntegerField()),
                ('employee_cuil', models.IntegerField()),
                ('employee_mobile', models.IntegerField()),
                ('employee_phone', models.IntegerField(blank=True, null=True)),
                ('employee_salary', models.IntegerField()),
                ('employe_active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_name', models.CharField(max_length=50)),
                ('position_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=100)),
                ('place_adress', models.CharField(max_length=100)),
                ('place_phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeTerm',
            fields=[
                ('term_id', models.IntegerField(primary_key=True, serialize=False)),
                ('term_salary', models.IntegerField()),
                ('term_enddate', models.DateField(blank=True, null=True)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.workplace'),
        ),
        migrations.AddField(
            model_name='employee',
            name='employee_position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.position'),
        ),
    ]
