# Generated by Django 4.0.3 on 2022-08-25 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeterm',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
