# Generated by Django 4.0.3 on 2022-08-25 21:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_alter_employeeterm_id_alter_position_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeterm',
            name='startdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
